### PR TITLE
Fixing issue #5: Adding retry pipe to some http requests

### LINKED ISSUE #5: Retry requests
When we send SLP, Leaderboard or Axie requests sometimes they can fail and we are left with a empty row e.g.

image

We should have a retry mechanism with a exponential back off time (lets say 3 retrys)

this will be needed for account-axies, leaderboard-stats, and slp-stats methods under:
image

### PR DESCRIPTION
**Pull request by nnkhuongduy**
Fixes #5 

Adding retry pipe to some http requests

### CODE REVIEW

File: src/app/services/user/helpers/account-axies.ts [hunk 1]
```diff
@@ -97,7 +98,7 @@ export class AccountAxies {
         const queryOutput: any = await this._apollo.query({
           query: GET_PROFILE_AXIES_BY_RONIN_ADDRESS,
           variables: variables,
-        }).toPromise();
+        }).pipe(retry(3)).toPromise();
```
Comment (Jsuppers) [inline src/app/services/user/helpers/account-axies.ts:101]: Ah cool, we can do this in the pipe. Maybe can we use the retryWhen to make a do a exponential back of. e.g. have a look at example 2 in https://www.learnrxjs.io/learn-rxjs/operators/error_handling/retrywhen

Comment (nnkhuongduy) [reply src/app/services/user/helpers/account-axies.ts]: I have added the retry strategy, please check it and let me know if you want to change it
